

### 수련생 회원 가입
POST http://localhost:8080/api/users/register
Content-Type: application/json

{
  "email" : "wjdwldus1010@daum.com",
  "password" : "wjdwldus9999uiui",
  "age" : 17,
  "sex" : "여자",
  "region" : "김해",
  "nickname" : "연어초밥",
  "mobile_number" : "010-7777-8888",
  "gymLocation" : "동상동"
}


### user 정보 업데이트
PUT http://localhost:8080/api/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ3amR3bGR1czEwMTBAZGF1bS5jb20iLCJpYXQiOjE3NTE1OTUwMjMsImV4cCI6MTc1MTU5NjgyM30.bsfrzGC3oTr7D4EWqrxggBiUPBG59pQ6HPXWskyTpMI

{
  "role" : "선수"
}

### 로그인
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "user_id" : "wjdwldus1010@daum.com",
  "user_password" : "wjdwldus9999uiui"
}

### 로그아웃
POST http://localhost:8080/api/auth/logout
Content-Type: application/json

### 비밀번호 업데이트
PUT http://localhost:8080/api/users/me/password

### user 삭제
DELETE http://localhost:8080/api/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ3amR3bGR1czk5OTlAZGF1bS5jb20iLCJpYXQiOjE3NTE1MzQwMTYsImV4cCI6MTc1MTUzNTgxNn0.ifPheM06L3LZ9be-eb8d0X-kT_7a1BqqjIt7kThjzv8

### 유저 목록을 조회하는 메서드
GET http://localhost:8080/api/users
Content-Type: application/json
Authorization:

### 관리자가 유저 목록 조회
GET http://localhost:8080/api/admin/users
Content-Type: application/json
Authorization:

### 관리자가 특정 유저의 상태를 변경
PUT http://localhost:8080/api/admin/users/9


### trainer 회원 가입


